Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2018-12, with the labels that each got.

#301 [GAPRINDASHVILI] Update to ruby 2.3.8
  kickstarts/partials/post/ruby_install.ks.erb
Labels: enhancement

#302 Update to ruby 2.4.5
  kickstarts/partials/post/ruby_install.ks.erb
Labels: enhancement, hammer/yes

#303 Don't execute the changelog
  CHANGELOG.md
Labels: changelog/no, cleanup
