Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2018-10, with the labels that each got.

#288 Add post compression support
  README.md
  scripts/spec/target_spec.rb
  scripts/target.rb
  scripts/vmbuild.rb
Labels: enhancement, gaprindashvili/yes, hammer/yes

#289 Compress Azure, HyperV and EC2 images
  scripts/target.rb
Labels: enhancement, gaprindashvili/yes, hammer/yes

#282 Move from apache module mod_auth_kerb to mod_auth_gssapi
  kickstarts/partials/packages/includes.ks.erb
Labels: enhancement

#290 Set commit_sha just once
  scripts/git_checkout.rb
Labels: bug, hammer/yes

#292 Add vspk python module for Nuage
  kickstarts/base.ks.erb
  kickstarts/partials/post/python_modules.ks.erb
Labels: enhancement, hammer/yes

#294 [HAMMER] [Changelog] Add updates for beta1.1
  CHANGELOG.md
Labels: documentation

#291 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#295 [Changelog] Add Sprint 97 and Hammer Beta1
  CHANGELOG.md
Labels: documentation, hammer/no
