Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2019-10, with the labels that each got.

#355 Configure network adapters during kickstart
  kickstarts/base.ks.erb
  kickstarts/partials/post/systemd.ks.erb
Labels: bug

#352 Setting delete at
  README.md
  scripts/Gemfile
  scripts/uploader.rb
Labels: enhancement

#356 Add activesupport to Gemfile
  scripts/Gemfile
Labels: enhancement

#357 Copy to devel
  scripts/uploader.rb
Labels: enhancement

#362 Bump resources for oz
  config/base.json
  config/base.json.azure
  scripts/vmbuild.rb
Labels: ivanchuk/yes

#361 Change how to identify running build
  bin/shared_functions.sh
Labels: ivanchuk/yes

#363 Run ruby/bundle install with parallel job option
  kickstarts/partials/post/bundler.ks.erb
  kickstarts/partials/post/ruby_install.ks.erb
Labels: ivanchuk/yes

#364 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: changelog/no, test

#365 Remove 'yarn cache clean' workaround
  kickstarts/partials/post/ui_compile.ks.erb
Labels: ivanchuk/yes, technical debt

#366 Use ENV variables for optional npm/yarn registry override
  README.md
  kickstarts/partials/post/npm_registry_setup.ks.erb
  kickstarts/partials/post/npm_yarn_registry_cleanup.ks.erb
  kickstarts/partials/post/ui_compile.ks.erb
  kickstarts/partials/post/yarn_registry_setup.ks.erb
Labels: enhancement, ivanchuk/yes
