Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2019-05, with the labels that each got.

#316 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: changelog/no, test

#317 Remove pglogical package
  kickstarts/partials/packages/includes.ks.erb
Labels: changelog/yes, enhancement, hammer/no

#320 Update to node 10
  kickstarts/partials/main/repos.ks.erb
Labels: changelog/yes, enhancement, hammer/no

#321 [Changelog] Update for Sprint 112
  CHANGELOG.md
Labels: documentation

#322 Add cockpit packages and changes to allow it to run by default
  kickstarts/partials/packages/includes.ks.erb
  kickstarts/partials/post/firewalld.ks.erb
  kickstarts/partials/post/systemd.ks.erb
Labels: changelog/yes, enhancement, hammer/no
