Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2019-08, with the labels that each got.

#333 Remove SCL related packages/repo - no longer used
  kickstarts/partials/main/repos.ks.erb
  kickstarts/partials/packages/includes.ks.erb
Labels: ivanchuk/yes

#334 Update to ovirt 4.3
  kickstarts/partials/post/ovirt_ansible.ks.erb
Labels: changelog/yes, ivanchuk/yes

#335 Remove bower
  kickstarts/partials/post/ui_compile.ks.erb
Labels: dependencies, technical debt

#336 Add libssh2-devel for rugged gem SSH support
  kickstarts/partials/packages/includes.ks.erb
Labels: embedded ansible

#337 Increase libvirt memory to 4GB to reduce build time
  config/base.json
Labels: ivanchuk/yes

#338 [Changelog] Update for Sprint 117
  CHANGELOG.md
Labels: documentation

#339 [Changelog] Update for Ivanchuk Beta2
  CHANGELOG.md
Labels: documentation

#341 Install python modules required for embedded ansible credentials
  kickstarts/partials/packages/includes.ks.erb
  kickstarts/partials/post/python_modules.ks.erb
Labels: bug, changelog/yes, embedded ansible, ivanchuk/yes

#343 [Changelog] Update for Sprint 118
  CHANGELOG.md
Labels: documentation

#344 [Changelog] Update for Ivanchuk RC1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#342 Add yarn available-languages to ui-service build
  kickstarts/partials/post/ui_compile.ks.erb
Labels: ivanchuk/yes

#345 Add option to use a different npm registry for yarn
  kickstarts/partials/post/ui_compile.ks.erb
Labels: ivanchuk/yes

#346 Update Google Compute Engine packages
  kickstarts/partials/post/gce.ks.erb
Labels: bug, ivanchuk/yes
