Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2019-07, with the labels that each got.

#325 Do not use unrecommended mount option nobarrier
  kickstarts/partials/main/disk_layout.ks.erb
Labels: changelog/yes, hammer/no

#326 [Changelog] Update for Sprint 115
  CHANGELOG.md
Labels: documentation

#327 Update to ruby 2.5.5
  kickstarts/partials/post/ruby_install.ks.erb
Labels: enhancement

#329 [Changelog] Update for Sprint 116
  CHANGELOG.md
Labels: documentation

#330 Temporary fix for asset compile error on Azure
  config/base.json.azure
  scripts/vmbuild.rb
Labels: hammer/yes, ivanchuk/yes

#331 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#332 Download the ansible-runner repo file rather than hardcoding the contents
  kickstarts/partials/post/repos.ks.erb
Labels: changelog/yes, embedded ansible, enhancement, ivanchuk/yes
