Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2019-09, with the labels that each got.

#347 Fix optional kickstart partial handling and add support for "npm install"
  kickstarts/partials/post/ui_compile.ks.erb
  scripts/kickstart_generator.rb
Labels: hammer/yes, ivanchuk/yes

#348 [Changelog] Rollup of Ivanchuk releases
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#350 [Changelog] Update for Sprint 120
  CHANGELOG.md
Labels: documentation
