Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2019-03, with the labels that each got.

#307 Temporarily downgrade qpid proton c library
  kickstarts/partials/post/bundler.ks.erb
Labels: bug, hammer/yes

#306 Change database paths and packages to PG 10
  kickstarts/partials/main/db_fs.ks.erb
  kickstarts/partials/packages/includes.ks.erb
  kickstarts/partials/post/db_init.ks.erb
Labels: enhancement, hammer/no, wip

#308 Remove temporary workaround to downgrade qpid-proton-c
  kickstarts/partials/post/bundler.ks.erb
Labels: hammer/no

#309 Don't exclude dracut-network package
  kickstarts/partials/packages/excludes.ks.erb
Labels: cleanup, hammer/no

#310 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation

#311 Exclude specific -firmware packages only
  kickstarts/partials/packages/excludes.ks.erb
Labels: hammer/no

#312 Update supported ruby versions on Travis
  .travis.yml
Labels: changelog/no, test
