Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2020-07, with the labels that each got.

#431 Create rpm manifest
  kickstarts/base.ks.erb
Labels: enhancement, jansa/yes?

#433 Send DigitalOcean delete_at under metadata, expires is for cache control
  scripts/uploader.rb
Labels: bug

#434 Fix undefined method `[]=' for nil:NilClass
  scripts/uploader.rb
Labels: bug, jansa/yes?
