Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2020-06, with the labels that each got.

#427 Replace yum with dnf
  README.md
  kickstarts/base.ks.erb
  kickstarts/partials/post/gce.ks.erb
  kickstarts/partials/post/ovirt_ansible.ks.erb
  kickstarts/partials/post/python_modules.ks.erb
  kickstarts/partials/post/repos.ks.erb
Labels: cleanup

#425 Add nightly yum repo only for non-release build
  bin/kickstart_build.rb
  kickstarts/partials/main/repos.ks.erb
  kickstarts/partials/post/repos.ks.erb
  scripts/kickstart_generator.rb
  scripts/spec/kickstart_generator_spec.rb
  scripts/vmbuild.rb
Labels: jansa/yes?

#426 Enforce root password reset at first login
  kickstarts/base.ks.erb
Labels: enhancement, jansa/yes?
