Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2020-04, with the labels that each got.

#409 Control qpid-proton rpm version by installing from ManageIQ copr repo
  kickstarts/partials/main/repos.ks.erb
  kickstarts/partials/post/repos.ks.erb
Labels: jansa/yes?

#410 [IVANCHUK] Control qpid-proton rpm version by installing from ManageIQ copr repo
  kickstarts/partials/main/repos.ks.erb
  kickstarts/partials/post/repos.ks.erb
Labels: bug

#412 Upload to multiple destinations
  scripts/uploader.rb
Labels: enhancement
