Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2020-03, with the labels that each got.

#388 Replace playground repo with epel
  kickstarts/partials/main/repos.ks.erb
Labels: enhancement, jansa/yes?

#390 Update gem clean up
  kickstarts/partials/post/bundler.ks.erb
Labels: cleanup

#396 Bundle with 'systemd' optional group
  kickstarts/partials/post/bundler.ks.erb
Labels: enhancement, jansa/yes?

#399 Add centos 8 download doc
  README.md
Labels: bug

#404 Don't error when upload is called without upload.yml
  scripts/uploader.rb
Labels: bug

#391 Resize and convert Azure disk
  scripts/fix_azure_disk.rb
  scripts/target.rb
  scripts/target_disk_converter.rb
  scripts/vmbuild.rb
Labels: bug

#406 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#407 Add BUILD_REF to podified build
  bin/container-build.sh
Labels: enhancement, jansa/yes
