Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2020-08, with the labels that each got.

#436 Stop uploading to Rackspace
  scripts/uploader.rb
Labels: cleanup, hammer/yes, ivanchuk/yes, jansa/yes?

#437 Lower CPU and Memory
  config/base.json
Labels: enhancement, jansa/yes?

#438 Change ifcfg-en* to eth0 after all post processing tasks are completed
  kickstarts/base.ks.erb
Labels: bug, jansa/yes?

#435 Add build type (release or nightly) support to container build
  bin/container-build.sh
  bin/nightly-build.sh
  bin/release-build.sh
Labels: enhancement, jansa/yes?
