Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2020-10, with the labels that each got.

#442 Remove PowerTools repo - no longer used
  kickstarts/partials/main/repos.ks.erb
  kickstarts/partials/post/repos.ks.erb
Labels: dependencies, technical debt

#444 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: dependencies

#445 Remove machine-id
  kickstarts/base.ks.erb
Labels: bug, jansa/yes?

#446 Allow for productization of build
  bin/kickstart_build.rb
  kickstarts/partials/main/repos.ks.erb
  kickstarts/partials/packages/includes.ks.erb
  kickstarts/partials/post/repos.ks.erb
  scripts/.gitignore
  scripts/cli.rb
  scripts/kickstart_generator.rb
  scripts/productization.rb
  scripts/spec/cli_spec.rb
  scripts/spec/data/prod/productization/test_prod_but_not_base
  scripts/spec/kickstart_generator_spec.rb
  scripts/spec/productization_spec.rb
  scripts/vmbuild.rb
Labels: enhancement

#419 Switch to manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
Labels: developer
