Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2020-05, with the labels that each got.

#414 Remove imagefactory_setup.sh
  bin/setup_imagefactory.sh
Labels: cleanup

#413 Add aws-sdk-s3 gem, needed for digital ocean upload
  scripts/Gemfile
Labels: changelog/no, ivanchuk/yes, jansa/yes

#416 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#418 Revert UCI image build changes
  scripts/cli.rb
  scripts/spec/cli_spec.rb
  scripts/spec/target_spec.rb
  scripts/spec/uploader_spec.rb
  scripts/target.rb
  scripts/uploader.rb
  scripts/vmbuild.rb
Labels: jansa/yes

#420 Update to oVirt 4.4 GA
  kickstarts/partials/main/repos.ks.erb
  kickstarts/partials/post/ovirt_ansible.ks.erb
Labels: jansa/yes

#417 Add building RPMs before starting appliance build
  .gitignore
  bin/nightly-build.sh
  bin/release-build.sh
  bin/rpm-build.sh
Labels: enhancement

#415 RPM based appliance build
  kickstarts/base.ks.erb
  kickstarts/partials/main/repos.ks.erb
  kickstarts/partials/packages/includes.ks.erb
  kickstarts/partials/post/bundler.ks.erb
  kickstarts/partials/post/python_modules.ks.erb
  kickstarts/partials/post/rake_tasks.ks.erb
  kickstarts/partials/post/repos.ks.erb
  kickstarts/partials/post/ruby_install.ks.erb
  kickstarts/partials/post/source_setup.ks.erb
  kickstarts/partials/post/ui_compile.ks.erb
Labels: enhancement

#421 Remove docbuild from nightly build
  bin/nightly-build.sh
  scripts/docbuild.rb
Labels: technical debt
