Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2021-09, with the labels that each got.

#488 Don't enable postfix in the kickstart
  kickstarts/partials/post/systemd.ks.erb
Labels: dependencies

#489 Bump pyyaml to 5.4 to handle CVEs
  kickstarts/partials/post/python_modules.ks.erb
Labels: dependencies, morphy/yes

#490 Don't exclude alsa, it's causing appliance image builds to fail
  kickstarts/partials/packages/excludes.ks.erb
Labels: bug
