Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2021-11, with the labels that each got.

#493 [MORPHY] Fix issue where the new branch might not have the updated repos
  kickstarts/partials/main/repos.ks.erb
  lib/tasks/release.rake
Labels: bug

#494 Installer issues
  config/base.json
  kickstarts/base.ks.erb
Labels: bug, morphy/yes

#495 Add kernel parameter to prevent saving kickstart config
  bin/iso_modify.sh
Labels: enhancement
