Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2021-03, with the labels that each got.

#464 Changes required by manageiq-pods#682
  bin/container-build.sh
Labels: bug

#465 Add registry to the docker commands
  bin/container-build.sh
Labels: enhancement

#466 Update the base image for the appliance build
  config/base.tdl.erb
Labels: enhancement

#463 In CentOS8, docker points to podman and containers don't run as root
  bin/rpm-build.sh
Labels: bug, kasparov/yes?, lasker/yes?

#468 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: dependencies

#471 [LASKER] Backport: Merge pull request #467 from bdunne/fileshare
  bin/nightly-build.sh
  scripts/cli.rb
Labels: cleanup

#470 Add starting the kafka server to the kickstart
  kickstarts/partials/post/appliance_init.ks.erb
Labels: enhancement
