Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2022-08, with the labels that each got.

#516 Remove appliance_init kickstarts
  kickstarts/base.ks.erb
Labels: bug

#517 Move manageiq venv to python 3.8
  kickstarts/partials/post/python_modules.ks.erb
Labels: bug, najdorf/yes?

#518 Ensure make is available on all platforms
  kickstarts/partials/post/python_modules.ks.erb
Labels: bug, najdorf/yes
