Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2022-09, with the labels that each got.

#519 Update python dependencies for CVEs
  kickstarts/partials/post/python_modules.ks.erb
Labels: dependencies, oparin/yes

#521 Update certain python dependencies for CVEs
  kickstarts/partials/post/python_modules.ks.erb
Labels: dependencies, security fix, oparin/yes

#522 Update certain python dependencies for CVEs
  kickstarts/partials/post/python_modules.ks.erb
Labels: security fix

#523 Remove transitive dependencies from the list of python packages
  kickstarts/partials/post/python_modules.ks.erb
Labels: dependencies

#524 Update appliances to use ruby 3
  kickstarts/base.ks.erb
Labels: ruby3

#527 Avoid installing weak dependencies
  kickstarts/base.ks.erb
Labels: enhancement

#528 Ensure psutil is installed for all pythons
  kickstarts/partials/post/python_modules.ks.erb
Labels: bug, oparin/yes

#529 Exclude epel-next-release rpm from being installed
  kickstarts/partials/packages/excludes.ks.erb
Labels: bug, oparin/yes?

#530 Revert "Merge pull request #528 from Fryguy/psutils"
  kickstarts/partials/post/python_modules.ks.erb
Labels: bug

#531 [OPARIN] Bump oauthlib to 3.2.1 for CVE-2022-36087
  kickstarts/partials/post/python_modules.ks.erb
Labels: security fix
