Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2022-02, with the labels that each got.

#507 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  Rakefile
Labels: developer, test

#508 Bump OVA default memory up to 16GB
  config/ova.json
Labels: enhancement, najdorf/yes?

#502 Update node version
  kickstarts/base.ks.erb
Labels: dependencies

#510 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
