Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2022-01, with the labels that each got.

#500 Document adding -joliet-long option to genisoimage
  README.md
Labels: documentation

#501 [MORPHY] Move to CentOS Stream
  README.md
  kickstarts/centos8_build_machine.ks
  kickstarts/partials/main/repos.ks.erb
Labels: enhancement

#499 Add ability to inspect the ISO for kickstart logging
  bin/iso_modify.sh
  config/base.tdl.erb
  scripts/vmbuild.rb
Labels: enhancement

#504 Fix whitesource config files
  .whitesource
Labels: cleanup
