Repository ManageIQ/manageiq-appliance-build, pull requests merged in 2024-11, with the labels that each got.

#577 test with ruby 3.3
  .github/workflows/ci.yaml
Labels: ruby3.3

#578 Set ruby stream to 3.3
  kickstarts/base.ks.erb
Labels: enhancement, ruby3.3

#579 [quinteros] Lock down to ruby 3.0.4 from Appstream
  kickstarts/partials/main/repos.ks.erb
  kickstarts/partials/packages/includes.ks.erb
  kickstarts/partials/post/repos.ks.erb
Labels: bug
